name: Docker

on:
  workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: configurando docker build
      uses: docker/setup-buildx-action@v2.0.0

    - name: download do build artifact
      uses: actions/download-artifact@v3.0.0
      with:
        name: programa
      
    - name: login no docker
      uses: docker/login-action@v2.0.0
      with:
        username: ${{ secrets.USER_DOCKER_HUB }}
        password: ${{ secrets.PASSWORD_DOCKER_HUB }}

    - name: build e push da imagem no Docker
      uses: docker/build-push-action@v3.0.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: brunooooooohenri/go_ci:${{ github.run_number }}