name: kubernetes

on:
  workflow_call:

jobs:

  eks:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3

      - name: configurando credenciais da aws
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      
      - name: clonando repositorio do github
        run: git clone https://github.com/BH-Tec/alura-formacao-ci-cd-kubernetes.git

      - name: hashiCorp - setup terraform
        uses: hashicorp/setup-terraform@v2.0.3

      - name: iniciando o terraform
        run: terraform -chdir=alura-formacao-ci-cd-kubernetes/env/Homolog init

      #
      - name: remove o terraform e impede de criar novamente.
        run: terraform -chdir=Infra_CI_Kubernetes/env/Homolog destroy -auto-approve
      - run: return 1
      #

      - run: terraform -chdir=alura-formacao-ci-cd-kubernetes/env/Homolog apply -auto-approve
      
      - name: Kubectl tool installer
        uses: Azure/setup-kubectl@v3

      - run: aws sts get-caller-identity

      - run: aws eks update-kubeconfig --region us-east-2 --name homolog2